name: Build distribution version on release
on:
  release:
    types: [created]

jobs:
  build-distribution-version-into-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
      - uses: actions/setup-node@v4
        name: Setup Node.js
        with:
          node-version: "20"
      - run: npm ci
        name: Install dependencies
      - run: npm run build
        name: Build distribution version
      - uses: actions/upload-artifact@v4
        name: Upload artifact
        with:
          name: build-${{ github.event.repository.name }}-${{ github.event.release.tag_name }}
          path: build
      - name: Zip dist folder
        run: zip -r ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.zip build
      - name: Upload file to existing release using gh cli
        run: gh release upload ${{ github.event.release.tag_name }} ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.zip
